"""внешний ключ hall_id убран у film, добавлен в filmsession

Revision ID: 2fd1eee31877
Revises: 3489f8e7d6f0
Create Date: 2025-04-01 16:45:39.294449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd1eee31877'
down_revision: Union[str, None] = '3489f8e7d6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('films_cinemahall_id_fkey', 'films', type_='foreignkey')
    op.drop_column('films', 'cinemahall_id')
    op.add_column('filmsessions', sa.Column('hall_id', sa.Integer(), nullable=True))
    op.alter_column('filmsessions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_foreign_key('filmsessions_hall_id_fkey', 'filmsessions', 'halls', ['hall_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('filmsessions_hall_id_fkey', 'filmsessions', type_='foreignkey')
    op.alter_column('filmsessions', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('filmsessions', 'hall_id')
    op.add_column('films', sa.Column('cinemahall_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('films_cinemahall_id_fkey', 'films', 'halls', ['cinemahall_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
