"""Добавлены модели кинотеатра и фильмов

Revision ID: a5a017b79814
Revises: 3fabbaed17ac
Create Date: 2024-11-29 22:13:29.008335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a017b79814'
down_revision: Union[str, None] = '3fabbaed17ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('halls',
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films',
    sa.Column('cinemahall_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('poster', sa.String(length=255), nullable=False),
    sa.Column('age_rating', sa.Enum('NO_RESTRICTION', 'KIDS', 'TEEN', 'YOUNG', 'ADULT', name='ageratingenum'), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('IN_RENT', 'ANNOUNCEMENT', name='filmstatusenum'), nullable=False),
    sa.Column('date_rent_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_rent_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['cinemahall_id'], ['halls.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rows',
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_genre_association',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'genre_id')
    )
    op.create_table('filmsessions',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['rows.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    op.drop_table('filmsessions')
    op.drop_table('film_genre_association')
    op.drop_table('rows')
    op.drop_table('films')
    op.drop_table('halls')
    op.drop_table('genres')
    # ### end Alembic commands ###
