"""добавлена можÐдель нотификаций

Revision ID: c8c3a0536b7f
Revises: 2bf8a1ea5f48
Create Date: 2025-02-27 18:42:03.712966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c3a0536b7f'
down_revision: Union[str, None] = '2bf8a1ea5f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=True),
    sa.Column('read_status', sa.Boolean(), nullable=False),
    sa.Column('send_status', sa.Enum('NOT_SENT', 'FAILED', 'SENT', name='notificationsendstatus'), nullable=False),
    sa.Column('kind', sa.Enum('CLIENT_GREETING', 'EMPLOYEE_GREETING', 'ORDER_COMPLETE', 'RESTORE_PASSWORD', 'NEW_FILM', 'SESSION_CANCELED', name='notificationkindenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
