"""Added capacity column to the rows

Revision ID: e0168449b43c
Revises: 5744a17f2cc3
Create Date: 2024-12-29 16:08:28.688377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0168449b43c'
down_revision: Union[str, None] = '5744a17f2cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rows', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rows', 'capacity')
    # ### end Alembic commands ###
